name: prime_flutter
description: "Pretty Rad Interactive Modular Elements. A collection of UI elements for Flutter, implementing Viam's design system."
version: 0.2.3
homepage: https://github.com/viamrobotics/prime_flutter
repository: https://github.com/viamrobotics/prime_flutter
documentation: https://design-mobile.viam.com

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  fonts:
    - family: PrimeIcons
      fonts:
        - asset: fonts/PrimeIcons.ttf
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono.ttf
        # - weight: 500

        

